from bot.game import *

game = Game()
game.join(Player(10, "Franz"))
game.join(Player(11, "Karl"))
game.join(Player(12, "Denzel"))
print(game.active_player)
game.next()
print(game.active_player)
game.next()
print(game.active_player)
game.next()
print(game.active_player)
game.reverse()
game.next()
print(game.active_player)
game.next()
print(game.active_player)
